#!/bin/bash
if [ ! -e "./run" ]
then
  echo "Please run this script from the example_data directory"
  exit 1
fi
R2RROOT=..
if [ $# == 0 ]
then
  echo "No Class to execute specified"
  exit 1
fi
CP=$R2RROOT
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in ${R2RROOT}/lib/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  CP="$CP$SEP$jar"
done
exec java -cp "$CP" -Xmx256M "$@"
